preload = /home/r2unit/.config/hypr/wallpapers/background1.jpg
preload = /home/r2unit/.config/hypr/wallpapers/background2.jpg
preload = /home/r2unit/.config/hypr/wallpapers/background3.jpg
wallpaper = ,/home/r2unit/.config/hypr/wallpapers/background1.jpg
splash = false
ipc = on